#!/usr/bin/env python3
"""
Dusk Personal Custom Setup (Arch Linux / Python 3.14+ / Firefox 140+)
========================================================================
Personal Firefox chrome customization that hides the redesigned sidebar for
*your* profiles only — deliberately separate from the shared Dusky Sites setup
(dusky_sites_setup.py) so other people who use your dotfiles are unaffected.
dusky_sites_setup.py is never modified or touched by this script.

───────────────────────────────────────────────────────────────────────────
CUSTOMIZATION — add / remove your own CSS blocks
───────────────────────────────────────────────────────────────────────────
Edit the PERSONAL_CSS_CONTENT block right below this docstring. It is the
single source of truth: every CSS rule you put there is written verbatim into
each profile's chrome/dusk_personal_custom.css. Add or remove rule blocks
freely (plain CSS, no escaping needed), then re-run this script to push the
changes into every profile.

───────────────────────────────────────────────────────────────────────────
What it does per profile:
  * Writes chrome/dusk_personal_custom.css   (PERSONAL_CSS_CONTENT, verbatim)
  * Adds its own @import line to chrome/userChrome.css
  * Ensures toolkit.legacyUserProfileCustomizations.stylesheets = true in user.js

Works hand-in-hand with dusky_sites_setup.py:
  * This script manages ONLY dusk_personal_custom.css and its own @import line.
    It never touches dusky_menu.css, dusky's imports, or dusky's config.
  * It never removes the shared `toolkit.legacyUserProfileCustomizations.stylesheets`
    pref while Dusky's chrome files are still referenced, so uninstalling this
    script can never break Dusky Sites.
  * `--uninstall` removes only the artifacts this script deployed into profiles.

Design guarantees:
  * Idempotent — safe to run any number of times; imports and prefs never
    duplicate, and already-correct files are left byte-for-byte untouched.
  * Atomic writes — every write goes through a temp file + fsync + same-directory
    rename, so a crash mid-write can never leave a truncated file behind.
  * Symlink-safe — writes *through* userChrome.css / user.js symlinks
    (dotfiles-friendly) instead of clobbering them.
  * Robust profile discovery — a deduplicated union of profiles.ini entries and
    a prefs.js/user.js directory scan, so orphan and never-yet-launched profiles
    are still covered. Non-profile dirs (Crash Reports, etc.) are skipped.

Usage:
  dusk_personal_custom.py              # install / ensure (pushes your CSS)
  dusk_personal_custom.py --uninstall  # remove only what this script deployed
  dusk_personal_custom.py --yes        # skip the confirmation prompt
  dusk_personal_custom.py --help
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

# ══════════════════════════════════════════════════════════════════════════
# YOUR PERSONAL CSS — EDIT THIS BLOCK
# ══════════════════════════════════════════════════════════════════════════
# This is the ONLY thing you need to edit. Add or remove rule blocks freely;
# the whole block below is written verbatim into every profile's
# chrome/dusk_personal_custom.css when you run this script.
#
# NOTE: this is a Python raw string. Write plain CSS exactly as you would in
# a .css file — no escaping needed. Keep at least one rule here, and never
# delete the three double-quotes that close the block below.
PERSONAL_CSS_CONTENT = r"""/* Auto-generated by Dusk Personal Custom — edit the PERSONAL_CSS_CONTENT
   block at the top of dusk_personal_custom.py to change these rules. */
/* Hides Firefox's built-in sidebar chrome (launcher rail, headers,
   drag splitters, AI window). Verified against the Firefox 153 DOM:
     #sidebar-container         — parent wrapper of the new unified sidebar
     sidebar-main               — the launcher rail (custom ELEMENT, not an ID!)
     #sidebar-header            — the classic panel header
     sidebar-panel-header       — the panel header (custom element)
     #sidebar-launcher-splitter — drag handle for the launcher
     #ai-window-box/splitter    — the separate AI chatbot window sidebar
   IMPORTANT: #sidebar-box is deliberately LEFT VISIBLE — native-sidebar
   extensions (Sidebery and similar) render their vertical tabs/panels
   inside it, and Firefox un-hides it whenever such a panel is open.
   Hiding #sidebar-box would hide your extension's sidebar too.
   The `#sidebar-splitter` resize handle is kept so Sidebery's panel width
   stays adjustable; add it to the list below if you want it gone too.
   NOTES on selectors:
   * Since the Firefox 136+ rewrite, `sidebar-main` is a custom ELEMENT,
     not an ID — the old `#sidebar-main { display:none }` rules match
     NOTHING on current Firefox. The `sidebar-main` element rule below is
     the one that actually removes the launcher rail.
   * `sidebar-panel-header` renders inside the sidebar's panel <browser>
     (a child document), which userChrome.css cannot style — that rule is
     currently inert and kept only as insurance; the launcher rail and
     containers above are what actually hide the sidebar chrome. */
#sidebar-container,
sidebar-main,
#sidebar-header,
sidebar-panel-header,
#sidebar-launcher-splitter,
#ai-window-box,
#ai-window-splitter {
  display: none !important;
}
"""


# ── CONFIG ──────────────────────────────────────────────────────────────
# Optional: also force Firefox back to the horizontal top tab strip by
# disabling its built-in vertical tabs (`sidebar.verticalTabs`). Only
# useful if you use an extension like Sidebery for the on-the-side tabs.
# Default False keeps the script purely CSS (it never touches tab prefs).
FORCE_HORIZONTAL_TABS = False


# ── Terminal styling ──────────────────────────────────────────────────────
C_CYAN = "\033[0;36m"
C_GREEN = "\033[0;32m"
C_BLUE = "\033[0;34m"
C_YELLOW = "\033[1;33m"
C_RESET = "\033[0m"


def print_step(msg: str) -> None:
    print(f"{C_BLUE}==>{C_RESET} {msg}")


def print_success(msg: str) -> None:
    print(f"{C_GREEN}✓{C_RESET} {msg}")


def print_warn(msg: str) -> None:
    print(f"{C_YELLOW}[!] {msg}")


# ── Identity (namespaced so it can never collide with Dusky's files) ──────
CSS_FILE_NAME = "dusk_personal_custom.css"
IMPORT_LINE = f'@import url("{CSS_FILE_NAME}");'

# The stylesheets pref is SHARED with dusky_sites_setup.py — it is only
# removed on uninstall while Dusky's chrome files are still referenced, so
# uninstalling this script can never silently break Dusky's theming.
SHARED_PREF = ("toolkit.legacyUserProfileCustomizations.stylesheets", "true")


def personal_prefs() -> list[tuple[str, str]]:
    """Prefs this script manages, computed at call time for the current CONFIG.

    Computing per call (instead of mutating a module-level constant) means
    install and uninstall always agree on the exact pref set for the
    ``FORCE_HORIZONTAL_TABS`` setting in effect, even if that knob changes
    between runs. Only ``SHARED_PREF`` is ever gated on Dusky's presence.
    """
    prefs = [SHARED_PREF]
    if FORCE_HORIZONTAL_TABS:
        prefs.append(("sidebar.verticalTabs", "false"))
    return prefs


_OUR_IMPORT_RE = re.compile(
    r"@import\s+url\(\s*[\"']?" + re.escape(CSS_FILE_NAME) + r"[\"']?\s*\)"
)


def _is_our_import(line: str) -> bool:
    """Robust check: is this an @import line that references our CSS file?

    Matches ``@import url("dusk_personal_custom.css");`` allowing optional
    whitespace and single/double quotes around the filename, plus trailing
    comments. Anchors the filename inside ``url(...)`` so unrelated imports
    (e.g. ``dusk_personal_custom_old.css``) can never false-positive — both
    when avoiding duplicate imports and when removing our import on uninstall.
    """
    return _OUR_IMPORT_RE.search(line) is not None


# ── Atomic, symlink-aware writes ──────────────────────────────────────────
def atomic_write_text(path: Path, text: str) -> None:
    """Write text atomically (temp file + fsync + same-dir rename).

    If ``path`` is a symlink (typical for dotfiles repos), write *through* it
    to the resolved target so the symlink is preserved, never replaced.
    Preserves the original file's permission bits, uses a unique temp name so
    concurrent runs can never race on the same temp file, and fsyncs the data
    to disk *before* the atomic rename — a crash at any point leaves either
    the old file or the complete new file, never a truncated one.
    """
    target = path.resolve() if path.is_symlink() else path
    target.parent.mkdir(parents=True, exist_ok=True)
    mode = None
    try:
        if target.is_file():
            mode = target.stat().st_mode
    except OSError:
        pass
    tmp = target.with_name(f".{target.name}.tmp{os.getpid()}")
    data = text.encode("utf-8")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o666)
    try:
        view = memoryview(data)
        written = 0
        while written < len(view):
            try:
                written += os.write(fd, view[written:])
            except InterruptedError:
                continue
        os.fsync(fd)
    finally:
        os.close(fd)
    if mode is not None:
        os.chmod(tmp, mode & 0o7777)
    os.replace(tmp, target)


def _remove_file(path: Path) -> bool:
    try:
        if path.is_symlink() or path.is_file():
            path.unlink()
            return True
    except OSError as e:
        print_warn(f"Could not remove {path}: {e}")
    return False


# ── user.js prefs (only the one pref this script needs) ───────────────────
def ensure_prefs(user_js: Path) -> bool:
    """Ensure the stylesheets pref is present with our value. Returns True if changed."""
    try:
        content = user_js.read_text(encoding="utf-8", errors="replace") if user_js.is_file() else ""
    except OSError as e:
        print_warn(f"Could not read {user_js}: {e}")
        return False
    original = content
    for pref_name, pref_val in personal_prefs():
        pref_re = re.compile(rf'user_pref\(\s*"{re.escape(pref_name)}"\s*,\s*[^)]+\)\s*;')
        pref_line = f'user_pref("{pref_name}", {pref_val});'
        if pref_re.search(content):
            content = pref_re.sub(pref_line, content)
        elif pref_line not in content:
            content = content.rstrip() + f"\n{pref_line}\n"
    if content != original:
        try:
            atomic_write_text(user_js, content)
            return True
        except OSError as e:
            print_warn(f"Could not write {user_js}: {e}")
            return False
    return False


def restore_pref_line(user_js: Path, prefs: list[tuple[str, str]]) -> bool:
    """Remove exact pref lines from ``prefs``. Returns True if any removed.

    Only exact lines matching the values this script would write are removed
    (an identical line written by hand is indistinguishable — the same
    exact-line pattern dusky_sites_setup.py uses).
    """
    exact_lines = [f'user_pref("{name}", {val});' for name, val in prefs]
    if not (user_js.is_file() or user_js.is_symlink()):
        return False
    try:
        content = user_js.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        print_warn(f"Could not read {user_js}: {e}")
        return False
    kept = [ln for ln in content.splitlines(keepends=True) if ln.strip() not in exact_lines]
    if len(kept) == len(content.splitlines(keepends=True)):
        return False
    try:
        atomic_write_text(user_js, "".join(kept))
        print_success(f"Removed pref line from {user_js}")
        return True
    except OSError as e:
        print_warn(f"Could not write {user_js}: {e}")
        return False


# ── Profile discovery (mirrors dusky_sites_setup.py, hardened) ────────────
def iter_firefox_profiles(base_dir: Path):
    """Yield profile directories: profiles.ini entries ∪ prefs.js/user.js scan (deduped).

    Using a union (rather than "ini only when present") means orphan profiles —
    real profile directories that exist but are not listed in profiles.ini —
    are still covered, while never-yet-launched profiles are caught by accepting
    ``user.js`` as well as ``prefs.js`` (Firefox writes prefs.js on first run,
    while user.js can already exist). Results are resolved, deduplicated, and
    sorted for deterministic order. Non-profile dirs (Crash Reports, Pending
    Pings, Profile Groups, etc.) contain neither file and are never yielded.
    """
    found: set[Path] = set()

    def emit(profile: Path) -> None:
        try:
            resolved = profile.resolve()
        except OSError:
            resolved = profile
        if resolved not in found:
            found.add(resolved)

    ini = base_dir / "profiles.ini"
    if ini.is_file():
        current: dict[str, str] = {}
        try:
            text = ini.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""

        def consider(cur: dict[str, str]) -> None:
            rel = cur.get("path")
            if not rel:
                return
            p = Path(rel)
            is_relative = cur.get("isrelative", "1") != "0"
            if is_relative:
                profile = base_dir / p
            else:
                profile = p if p.is_absolute() else (base_dir / p)
            try:
                if profile.is_dir():
                    emit(profile)
            except OSError:
                if profile.is_dir():
                    emit(profile)

        for line in text.splitlines():
            line = line.strip()
            if line.startswith("[") and line.endswith("]"):
                consider(current)
                current = {}
            elif "=" in line:
                k, v = line.split("=", 1)
                current[k.strip().lower()] = v.strip()
        consider(current)

    try:
        for profile in base_dir.iterdir():
            if profile.is_dir() and (
                (profile / "prefs.js").is_file() or (profile / "user.js").is_file()
            ):
                emit(profile)
    except OSError:
        pass

    yield from sorted(found, key=str)


def _profile_base_dirs(home: Path) -> list[Path]:
    """Firefox-family profile roots (same list as Dusky Sites)."""
    return [
        home / ".mozilla" / "firefox",
        home / ".config" / "mozilla" / "firefox",
        home / ".librewolf",
        home / ".config" / "librewolf",
        home / ".zen",
        home / ".config" / "zen",
        home / ".waterfox",
        home / ".floorp",
        home / ".firedragon",
        home / ".var" / "app" / "org.mozilla.firefox" / ".mozilla" / "firefox",
        home / ".var" / "app" / "io.gitlab.librewolf-community" / ".librewolf",
    ]


def _browser_processes_running() -> list[str]:
    """Return names of detected running Firefox-family browsers (informational).

    Runs one `pgrep -x` per browser name. (`pgrep -x` requires an exact
    process-name match, so a single pipe-delimited pattern like
    ``"firefox|librewolf"`` would never match anything.)
    """
    import subprocess
    names: set[str] = set()
    for browser in ("firefox", "librewolf", "zen", "waterfox", "floorp", "firedragon"):
        try:
            proc = subprocess.run(["pgrep", "-x", browser], capture_output=True, text=True)
        except OSError:
            continue
        if proc.returncode == 0 and proc.stdout.strip():
            names.add(browser)
    return sorted(names)


# ── Per-profile install / restore ─────────────────────────────────────────
def setup_profile(profile: Path) -> bool:
    """Install CSS + import + pref into one profile. Returns True if anything changed."""
    changed = False
    if ensure_prefs(profile / "user.js"):
        changed = True

    chrome_dir = profile / "chrome"
    try:
        chrome_dir.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        print_warn(f"Could not create {chrome_dir}: {e}")
        return changed

    # CSS file — write only if missing or different (idempotent; picks up edits
    # to PERSONAL_CSS_CONTENT).
    css_path = chrome_dir / CSS_FILE_NAME
    try:
        if css_path.is_file() and css_path.read_text(encoding="utf-8", errors="replace") == PERSONAL_CSS_CONTENT:
            pass
        else:
            atomic_write_text(css_path, PERSONAL_CSS_CONTENT)
            changed = True
    except OSError as e:
        print_warn(f"Could not write {css_path}: {e}")

    # @import line — add only if not already present (idempotent; whitespace-insensitive).
    uc_path = chrome_dir / "userChrome.css"
    try:
        existing = uc_path.read_text(encoding="utf-8", errors="replace") if uc_path.is_file() else ""
        already_imported = any(_is_our_import(ln) for ln in existing.splitlines())
        if already_imported:
            pass
        else:
            if existing.strip():
                new_content = f"{IMPORT_LINE}\n\n{existing}"
            else:
                new_content = f"{IMPORT_LINE}\n"
            atomic_write_text(uc_path, new_content)
            changed = True
    except OSError as e:
        print_warn(f"Could not write {uc_path}: {e}")

    return changed


def _dusky_chrome_present(chrome_dir: Path) -> bool:
    """True if Dusky's chrome files are still in use — keeps the shared pref alive.

    Checks both menu (userChrome) and content (userContent) theming, matching the
    real-world files (dusky_menu.css / dusky_content.css), so uninstalling this
    script can never silently break Dusky's web-content theming either.
    """
    try:
        if (chrome_dir / "dusky_menu.css").is_file():
            return True
        if (chrome_dir / "dusky_content.css").is_file():
            return True
        for uc_name in ("userChrome.css", "userContent.css"):
            uc = chrome_dir / uc_name
            if uc.is_file():
                text = uc.read_text(encoding="utf-8", errors="replace")
                if "dusky_menu.css" in text or "dusky_content.css" in text:
                    return True
    except OSError:
        pass
    return False


def restore_profile(profile: Path) -> bool:
    """Remove this script's deployed artifacts from one profile. Returns True if any removed."""
    chrome_dir = profile / "chrome"
    removed = False
    if chrome_dir.is_dir():
        css_path = chrome_dir / CSS_FILE_NAME
        if _remove_file(css_path):
            print_success(f"Removed {css_path}")
            removed = True

        uc_path = chrome_dir / "userChrome.css"
        uc_changed = False
        if uc_path.is_file() or uc_path.is_symlink():
            try:
                lines = uc_path.read_text(encoding="utf-8", errors="replace").splitlines()
            except OSError as e:
                print_warn(f"Could not read {uc_path}: {e}")
                return removed
            kept = [ln for ln in lines if not _is_our_import(ln)]
            uc_changed = len(kept) != len(lines)
            if uc_changed:
                while kept and kept[0].strip() == "":
                    kept.pop(0)
                new_text = "\n".join(kept).rstrip() + "\n"
                if new_text.strip():
                    try:
                        atomic_write_text(uc_path, new_text)
                        print_success(f"Removed import from {uc_path}")
                    except OSError as e:
                        print_warn(f"Could not write {uc_path}: {e}")
                else:
                    # File held nothing but our import. For a symlink (dotfiles),
                    # write the empty state through to the resolved target so the
                    # symlink survives and no stale @import is left behind; for a
                    # plain file, just delete it.
                    if uc_path.is_symlink():
                        try:
                            atomic_write_text(uc_path, "")
                            print_success(f"Emptied {uc_path} (symlink target)")
                        except OSError as e:
                            print_warn(f"Could not empty {uc_path}: {e}")
                    else:
                        _remove_file(uc_path)
                        print_success(f"Removed empty {uc_path}")
                removed = True

        # Optional knob pref (sidebar.verticalTabs=false) is never shared with
        # Dusky. Remove it unconditionally — the exact-line match makes this a
        # safe no-op if it was never written, and it stays correct even if
        # FORCE_HORIZONTAL_TABS was changed between install and uninstall.
        if restore_pref_line(profile / "user.js", [("sidebar.verticalTabs", "false")]):
            removed = True

        # Shared pref: only remove if Dusky isn't still using userChrome.
        if not _dusky_chrome_present(chrome_dir):
            if restore_pref_line(profile / "user.js", [SHARED_PREF]):
                removed = True
    return removed


# ── Install / uninstall drivers ───────────────────────────────────────────
def run_install(home: Path) -> None:
    print(f"\n{C_CYAN}Dusk Personal Custom Setup (Arch Linux / Python 3.14+){C_RESET}\n")

    running = _browser_processes_running()
    if running:
        print_warn(f"Detected running browser(s): {', '.join(running)}")
        print_warn("Changes will take effect at the next browser restart.")

    print_step("Scanning Firefox-family profiles...")
    touched = 0
    total = 0
    for base_dir in _profile_base_dirs(home):
        if not base_dir.is_dir():
            continue
        for profile in iter_firefox_profiles(base_dir):
            total += 1
            if setup_profile(profile):
                touched += 1
            print_success(f"Ensured personal custom in {profile}")

    if total == 0:
        print_warn("No Firefox-family profiles found. Nothing to do.")
        return
    if touched == 0:
        print_success(f"All {total} profile(s) already up to date — no changes needed.")
    else:
        print_success(f"Updated {touched}/{total} profile(s).")

    print(f"\n{C_GREEN}[+] Setup complete. Restart your browser to apply the CSS.{C_RESET}\n")


def run_uninstall(home: Path) -> None:
    print(f"\n{C_CYAN}[-] Dusk Personal Custom Uninstaller{C_RESET}\n")

    running = _browser_processes_running()
    if running:
        print_warn(f"Detected running browser(s): {', '.join(running)}")
        print_warn("It is strongly recommended to close them before continuing.")

    print_step("Removing deployed personal custom artifacts...")
    removed_any = 0
    for base_dir in _profile_base_dirs(home):
        if not base_dir.is_dir():
            continue
        for profile in iter_firefox_profiles(base_dir):
            if restore_profile(profile):
                removed_any += 1

    if removed_any == 0:
        print_warn("No personal custom artifacts found to remove.")
    else:
        print_success(f"Cleaned {removed_any} profile(s).")

    print(f"\n{C_GREEN}[+] Uninstall complete. Dusky Sites artifacts were left untouched.{C_RESET}\n")


def main() -> None:
    args = [a for a in sys.argv[1:]]

    if "--help" in args or "-h" in args:
        print(__doc__)
        print("Options:")
        print("  --uninstall   Remove deployed CSS/import/pref from profiles.")
        print("  --yes         Skip the confirmation prompt.")
        return

    if "--uninstall" in args or "--purge" in args:
        auto_yes = "--yes" in args
        if not auto_yes:
            try:
                resp = input(
                    "Are you sure you want to uninstall Dusk Personal Custom (sidebar hider)? [y/N] "
                ).strip().lower()
            except EOFError:
                resp = "n"
            if resp not in ("y", "yes"):
                print("Aborted.")
                return
        run_uninstall(Path.home())
        return

    run_install(Path.home())


if __name__ == "__main__":
    main()
