import xml.etree.ElementTree as ET
from xml.dom import minidom
from pathlib import Path
from typing import Any
import subprocess

from python.frontend.core_types import BaseEngine

class FontconfigEngine(BaseEngine):
    """
    O(1) XML serialization engine for Arch Linux fontconfig rules.
    Operates strictly within ~/.config/fontconfig/conf.d/ to adhere to XDG standards.
    """
    def __init__(self, config_path: str = "~/.config/fontconfig/conf.d/99-dusky-fonts.conf"):
        self.config_path = Path(config_path).expanduser().resolve()
        self.cache: dict[str, Any] = {}

    @property
    def target_path(self) -> str:
        return str(self.config_path)

    def load_state(self) -> dict[str, Any]:
        if not self.config_path.exists() or self.config_path.stat().st_size == 0:
            return {}

        state = {}
        try:
            tree = ET.parse(self.config_path)
            root = tree.getroot()

            # Parse Font Aliases (sans-serif, serif, monospace, emoji, etc.)
            for alias in root.findall('alias'):
                family_elem = alias.find('family')
                if family_elem is not None and family_elem.text:
                    family = family_elem.text.strip()
                    prefer_elem = alias.find('prefer/family')
                    if prefer_elem is not None and prefer_elem.text:
                        state[family] = prefer_elem.text.strip()

            # Parse Subpixel Rendering & Hinting Configuration across match blocks
            for match in root.findall("match"):
                for edit in match.findall('edit'):
                    name = edit.get('name')
                    if name:
                        bool_val = edit.find('bool')
                        if bool_val is not None:
                            state[name] = bool_val.text.strip().lower() in ("true", "1", "yes", "on", "t", "y")
                        
                        const_val = edit.find('const')
                        if const_val is not None:
                            state[name] = const_val.text.strip()
            self.cache = state
        except Exception as e:
            print(f"[FontconfigEngine] Load Exception: {e}")
            
        return state

    def write_batch(self, changes: list[tuple[str, str, str, str]]) -> tuple[bool, str, str]:
        if not changes:
            return True, "No pending changes.", ""

        state = self.load_state()
        known_bool_keys = {"antialias", "hinting", "autohint", "embeddedbitmap", "subpixel"}

        for key, scope, val, itype in changes:
            if itype == "bool" or key in known_bool_keys or isinstance(val, bool):
                if isinstance(val, bool):
                    state[key] = val
                else:
                    state[key] = str(val).lower() in ("true", "1", "yes", "on", "t", "y")
            else:
                state[key] = val

        try:
            self.config_path.parent.mkdir(parents=True, exist_ok=True)
            
            root = ET.Element('fontconfig')

            # 1. Generate Alias Blocks
            font_classes = ['sans-serif', 'serif', 'monospace', 'emoji']
            for fc in font_classes:
                if fc in state:
                    alias = ET.SubElement(root, 'alias', {'binding': 'strong'})
                    fam = ET.SubElement(alias, 'family')
                    fam.text = fc
                    pref = ET.SubElement(alias, 'prefer')
                    pref_fam = ET.SubElement(pref, 'family')
                    pref_fam.text = str(state[fc])

            # 2. Generate Rendering Match Block (for non-alias fontconfig keys)
            render_keys = [k for k in state if k not in font_classes]
            if render_keys:
                match = ET.SubElement(root, 'match', {'target': 'font'})
                for k in render_keys:
                    edit = ET.SubElement(match, 'edit', {'mode': 'assign', 'name': k})
                    if isinstance(state[k], bool):
                        b = ET.SubElement(edit, 'bool')
                        b.text = "true" if state[k] else "false"
                    else:
                        c = ET.SubElement(edit, 'const')
                        c.text = str(state[k])

            # 3. Format and clean XML string
            xmlstr = minidom.parseString(ET.tostring(root)).toprettyxml(indent="  ")
            
            # Inject correct DOCTYPE
            xmlstr = xmlstr.replace(
                '<?xml version="1.0" ?>', 
                '<?xml version="1.0"?>\n<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">'
            )
            
            # Strip empty lines generated by minidom's text node artifacts
            clean_xml = "\n".join(line for line in xmlstr.split('\n') if line.strip()) + "\n"

            # 4. Atomic Write
            temp_path = self.config_path.with_suffix('.tmp')
            with open(temp_path, 'w', encoding='utf-8') as f:
                f.write(clean_xml)
            temp_path.replace(self.config_path)

            self.cache = state
            
            # 5. Non-blocking System Cache Refresh (fail-safe)
            try:
                subprocess.Popen(
                    ["fc-cache", "-f"], 
                    stdout=subprocess.DEVNULL, 
                    stderr=subprocess.DEVNULL
                )
            except Exception:
                pass
            
            return True, f"Successfully applied {len(changes)} font settings.", ""
            
        except Exception as e:
            return False, f"XML Generation Failed: {e}", ""

    def write_value(self, target_key: str, target_scope: str, new_value: str, item_type: str = "string") -> tuple[bool, str, str]:
        return self.write_batch([(target_key, target_scope, new_value, item_type)])
